import './globals.css'
import type { Metadata } from 'next'
import { Mooli } from 'next/font/google'
import NextUIProviders from './nextui.provider'
import { NavigationBar } from '@app/_components'
import ReduxProviders from '@redux'
import { ConfirmTransaction } from './_components/ConfirmTransaction'
import { TokenData, readTokenPrices, writeTokenPrices } from '../api'


const font = Mooli({ weight: '400', subsets : ['latin'] })

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

const RootLayout = ({
    children,
}: {
  children: React.ReactNode
}) => {
    return ( <html lang="en" suppressHydrationWarning className="light text-foreground bg-background">
        <body className={font.className}>
            <NextUIProviders>
                <ReduxProviders>
                    <NavigationBar />
                    <ConfirmTransaction />
                    {children}
                </ReduxProviders>
            </NextUIProviders>
        </body>
    </html>
    )
}

export const getServerSideProps = async () => {
    let tokenData: TokenData[] | null = readTokenPrices()

    if (tokenData == null) {
        tokenData = await writeTokenPrices()
    }

    return {
        props: {
            tokenData,
        },
    }
}

export default RootLayout
